/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'inv',
    path: '/inv',
    component: 'layout.base',
    meta: {
      title: 'inv',
      i18nKey: 'route.inv',
      icon: 'mdi:invoice-text-outline',
      order: 1,
      roles: ['R_SUPER', 'R_ADMIN']
    },
    children: [
      {
        name: 'inv_dashboard',
        path: '/inv/dashboard',
        component: 'view.inv_dashboard',
        meta: {
          title: 'inv_dashboard',
          i18nKey: 'route.inv_dashboard',
          icon: 'mdi:chart-box-outline',
          order: 0,
          roles: ['R_SUPER', 'R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'inv_invoice',
        path: '/inv/invoice',
        component: 'view.inv_invoice',
        meta: {
          title: 'inv_invoice',
          i18nKey: 'route.inv_invoice',
          icon: 'mdi:receipt-text-outline',
          order: 2,
          roles: ['R_SUPER', 'R_ADMIN'],
          keepAlive: true
        }
      },
      {
        name: 'inv_task',
        path: '/inv/task',
        component: 'view.inv_task',
        meta: {
          title: 'inv_task',
          i18nKey: 'route.inv_task',
          icon: 'mdi:file-document-multiple-outline',
          order: 1,
          roles: ['R_SUPER', 'R_ADMIN'],
          keepAlive: true
        }
      }
    ]
  },
  {
    name: 'inv-user',
    path: '/inv-user',
    component: 'layout.base$view.inv-user',
    meta: {
      title: 'inv-user',
      i18nKey: 'route.inv-user',
      icon: 'mdi:account-group-outline',
      order: 2,
      roles: ['R_SUPER', 'R_ADMIN'],
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 9,
      roles: ['R_SUPER']
    },
    children: [
      {
        name: 'manage_app',
        path: '/manage/app',
        component: 'view.manage_app',
        meta: {
          title: 'manage_app',
          i18nKey: 'route.manage_app',
          icon: 'mdi:view-grid-outline',
          order: 4,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'manage_config',
        path: '/manage/config',
        component: 'view.manage_config',
        meta: {
          title: 'manage_config',
          i18nKey: 'route.manage_config',
          icon: 'mdi:cog-outline',
          order: 5,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'manage_log',
        path: '/manage/log',
        component: 'view.manage_log',
        meta: {
          title: 'manage_log',
          i18nKey: 'route.manage_log',
          icon: 'mdi:clipboard-list-outline',
          order: 6,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          order: 3,
          roles: ['R_SUPER'],
          keepAlive: true
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          order: 2,
          roles: ['R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          roles: ['R_SUPER']
        }
      }
    ]
  }
];
